name: ServerQueue
version: '1.3.2'
main: nl.jouwapplicatie.serverQueue.ServerQueue
api-version: '1.21'
authors: ['jonawoning']
description: A plugin that provides a queue for you to connect to servers.
commands:
  serverqueue:
    description: The main plugin command.
    aliases: [sq]
  queue:
    description: Join a server queue.
    aliases: [q]
  qlsystem:
    description: Set a pause for the queue.
    aliases: [qsystem, queuesystem]
